### ISSUE TITLE
Ability to have a callback that returns multiples scanned barcode for the same trigger

### ISSUE THREAD

**Issue by FlavienDuPeloux** [philpettican/react-native-unitech-scanner#2]
Hello @philpettican 

Currently, i'm using the lib with ScanManager.addEventListener method, and it works pretty well.
The thing is, sometimes there are 2 barcodes (or more often 1 barcode and 1 datamatrix) that are very close to each other.
So close that if i want to scan barcode "A", the first returned barcode is datamatrix "B". I have to retry multiple times and after some tries and luck i am finally able to receive barcode "A".
This issue makes it hardly usable and causes some frustrations

Is there a way to have a new method that returns every scanned barcode until i find one that matches the requirements ?
Or maybe i am not correctly using the package...

I would like to discuss it with you, and maybe also contribute if it's just a matter of time

Cheers

**Comment by philpettican** [comment]
Hi @BooYah112 ,

If you go to https://portal.unitech.eu/Products and search for **EA510**, then click on the **SDK Source** tab, you'll be able to download the SDK and example code. The SDK version this library is currently using is [v4.0.0115](https://github.com/philpettican/react-native-unitech-scanner/tree/master/android/libs) and it looks like the latest download available is v4.1.0326. The download also includes an APK (ScannerTestEAV1.3.2.apk) which can be used to explore the features available in the SDK.

What I'd do is download and install the ScannerTestEAV1.3.2.apk app on your device and see whether the SDK supports what you're after and also have a look through the SDK-API samples.

In the end, all this library does is provide an interface to the SDK, so if the SDK supports it, you'll be able to add the bridge to it.

Unfortunately I don't have access to an EA510 device now as we had it on loan from a customer but hopefully this gives you something to go on.
